name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202'
    - name: Publish project
      run: dotnet publish -c Release -r linux-x64 -o deploy
    - name: Generate command list
      run: /home/runner/work/Shine/Shine/deploy/Shine /GenerateMarkdown=true
    - name: Copy command list to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "docs"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    - name: Copy via SSH
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Shine/Shine/deploy/
        remote: ${{ secrets.REMOTE_DIR }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSHKEY }}
    - name: Restart service
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: systemctl restart bot
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSHKEY }}
