name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'
    - name: Publish project
      run: dotnet publish -c Release -o deploy
    - name: Get unlost
      run: ls -R
      working-directory: /home/runner/work
    - name: Copy via SSH
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/QuantumToasted/QuantumToasted/deploy/
        remote: ${{ secrets.REMOTE_DIR }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSHKEY }}
    - name: Restart service
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: systemctl restart bot
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSHKEY }}
